// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: db.proto

/*
Package go_micro_srv_db is a generated protocol buffer package.

It is generated from these files:
	db.proto

It has these top-level messages:
	Message
	DeleteUserRequest
	DeleteUserResponse
	GetUserRequest
	GetUserResponse
	UpdateUserRequest
	UpdateUserResponse
	Response
	StreamingRequest
	StreamingResponse
	Ping
	Pong
*/
package go_micro_srv_db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DB service

type DBClient interface {
	GetUserById(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*GetUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...client.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...client.CallOption) (*DeleteUserResponse, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (DB_StreamClient, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (DB_PingPongClient, error)
}

type dBClient struct {
	c           client.Client
	serviceName string
}

func NewDBClient(serviceName string, c client.Client) DBClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.db"
	}
	return &dBClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dBClient) GetUserById(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*GetUserResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.GetUserById", in)
	out := new(GetUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...client.CallOption) (*UpdateUserResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.UpdateUser", in)
	out := new(UpdateUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...client.CallOption) (*DeleteUserResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.DeleteUser", in)
	out := new(DeleteUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (DB_StreamClient, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &dBStreamClient{stream}, nil
}

type DB_StreamClient interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type dBStreamClient struct {
	stream client.Streamer
}

func (x *dBStreamClient) Close() error {
	return x.stream.Close()
}

func (x *dBStreamClient) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *dBStreamClient) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *dBStreamClient) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dBClient) PingPong(ctx context.Context, opts ...client.CallOption) (DB_PingPongClient, error) {
	req := c.c.NewRequest(c.serviceName, "DB.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &dBPingPongClient{stream}, nil
}

type DB_PingPongClient interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type dBPingPongClient struct {
	stream client.Streamer
}

func (x *dBPingPongClient) Close() error {
	return x.stream.Close()
}

func (x *dBPingPongClient) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *dBPingPongClient) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *dBPingPongClient) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *dBPingPongClient) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for DB service

type DBHandler interface {
	GetUserById(context.Context, *GetUserRequest, *GetUserResponse) error
	UpdateUser(context.Context, *UpdateUserRequest, *UpdateUserResponse) error
	DeleteUser(context.Context, *DeleteUserRequest, *DeleteUserResponse) error
	Stream(context.Context, *StreamingRequest, DB_StreamStream) error
	PingPong(context.Context, DB_PingPongStream) error
}

func RegisterDBHandler(s server.Server, hdlr DBHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DB{hdlr}, opts...))
}

type DB struct {
	DBHandler
}

func (h *DB) GetUserById(ctx context.Context, in *GetUserRequest, out *GetUserResponse) error {
	return h.DBHandler.GetUserById(ctx, in, out)
}

func (h *DB) UpdateUser(ctx context.Context, in *UpdateUserRequest, out *UpdateUserResponse) error {
	return h.DBHandler.UpdateUser(ctx, in, out)
}

func (h *DB) DeleteUser(ctx context.Context, in *DeleteUserRequest, out *DeleteUserResponse) error {
	return h.DBHandler.DeleteUser(ctx, in, out)
}

func (h *DB) Stream(ctx context.Context, stream server.Streamer) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.DBHandler.Stream(ctx, m, &dBStreamStream{stream})
}

type DB_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type dBStreamStream struct {
	stream server.Streamer
}

func (x *dBStreamStream) Close() error {
	return x.stream.Close()
}

func (x *dBStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *dBStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *dBStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *DB) PingPong(ctx context.Context, stream server.Streamer) error {
	return h.DBHandler.PingPong(ctx, &dBPingPongStream{stream})
}

type DB_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type dBPingPongStream struct {
	stream server.Streamer
}

func (x *dBPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *dBPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *dBPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *dBPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *dBPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
