// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

/*
Package go_micro_srv_db is a generated protocol buffer package.

It is generated from these files:
	db.proto

It has these top-level messages:
	Message
	DeleteUserRequest
	DeleteUserResponse
	GetUserRequest
	GetUserResponse
	UpdateUserRequest
	UpdateUserResponse
	Response
	StreamingRequest
	StreamingResponse
	Ping
	Pong
*/
package go_micro_srv_db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Say string `protobuf:"bytes,1,opt,name=say" json:"say,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type DeleteUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeleteUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Id     int64  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserResponse) Reset()                    { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()               {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DeleteUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserResponse struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Sex         string `protobuf:"bytes,3,opt,name=sex" json:"sex,omitempty"`
	Address     string `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Email       string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	PortraitUrl string `protobuf:"bytes,6,opt,name=portrait_url,json=portraitUrl" json:"portrait_url,omitempty"`
	CreateTime  int32  `protobuf:"varint,7,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime  int32  `protobuf:"varint,8,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserResponse) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *GetUserResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserResponse) GetPortraitUrl() string {
	if m != nil {
		return m.PortraitUrl
	}
	return ""
}

func (m *GetUserResponse) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *GetUserResponse) GetUpdateTime() int32 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type GetUserResponse_Address struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Shortname string `protobuf:"bytes,2,opt,name=shortname" json:"shortname,omitempty"`
	Address   string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *GetUserResponse_Address) Reset()                    { *m = GetUserResponse_Address{} }
func (m *GetUserResponse_Address) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse_Address) ProtoMessage()               {}
func (*GetUserResponse_Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *GetUserResponse_Address) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponse_Address) GetShortname() string {
	if m != nil {
		return m.Shortname
	}
	return ""
}

func (m *GetUserResponse_Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetUserResponse_MobilePhone struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PhoneNumber string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	Shortname   string `protobuf:"bytes,3,opt,name=shortname" json:"shortname,omitempty"`
}

func (m *GetUserResponse_MobilePhone) Reset()                    { *m = GetUserResponse_MobilePhone{} }
func (m *GetUserResponse_MobilePhone) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse_MobilePhone) ProtoMessage()               {}
func (*GetUserResponse_MobilePhone) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 1} }

func (m *GetUserResponse_MobilePhone) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponse_MobilePhone) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *GetUserResponse_MobilePhone) GetShortname() string {
	if m != nil {
		return m.Shortname
	}
	return ""
}

type UpdateUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateUserResponse struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Sex         string `protobuf:"bytes,3,opt,name=sex" json:"sex,omitempty"`
	Address     string `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Email       string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	PortraitUrl string `protobuf:"bytes,6,opt,name=portrait_url,json=portraitUrl" json:"portrait_url,omitempty"`
	CreateTime  int32  `protobuf:"varint,7,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime  int32  `protobuf:"varint,8,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
}

func (m *UpdateUserResponse) Reset()                    { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()               {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserResponse) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *UpdateUserResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UpdateUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserResponse) GetPortraitUrl() string {
	if m != nil {
		return m.PortraitUrl
	}
	return ""
}

func (m *UpdateUserResponse) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *UpdateUserResponse) GetUpdateTime() int32 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamingRequest struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *StreamingRequest) Reset()                    { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()               {}
func (*StreamingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *StreamingResponse) Reset()                    { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()               {}
func (*StreamingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke int64 `protobuf:"varint,1,opt,name=stroke" json:"stroke,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke int64 `protobuf:"varint,1,opt,name=stroke" json:"stroke,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.db.Message")
	proto.RegisterType((*DeleteUserRequest)(nil), "go.micro.srv.db.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "go.micro.srv.db.DeleteUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "go.micro.srv.db.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "go.micro.srv.db.GetUserResponse")
	proto.RegisterType((*GetUserResponse_Address)(nil), "go.micro.srv.db.GetUserResponse.Address")
	proto.RegisterType((*GetUserResponse_MobilePhone)(nil), "go.micro.srv.db.GetUserResponse.MobilePhone")
	proto.RegisterType((*UpdateUserRequest)(nil), "go.micro.srv.db.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "go.micro.srv.db.UpdateUserResponse")
	proto.RegisterType((*Response)(nil), "go.micro.srv.db.Response")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.db.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.db.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.db.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.db.Pong")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xe3, 0xfc, 0x4e, 0x50, 0x9b, 0xae, 0x0a, 0xb2, 0x4c, 0x45, 0xd3, 0xed, 0x25, 0x5c,
	0xac, 0x0a, 0xae, 0x08, 0x89, 0xaa, 0x12, 0xe2, 0x50, 0x54, 0x5c, 0x22, 0x6e, 0x44, 0x4e, 0x3c,
	0x72, 0x57, 0xd8, 0xde, 0xb0, 0xbb, 0x46, 0xed, 0x53, 0xf0, 0x08, 0x3c, 0x1a, 0xaf, 0x82, 0xbc,
	0x5e, 0x27, 0x8e, 0xed, 0xe6, 0x01, 0xb8, 0x79, 0xbe, 0xf9, 0xe6, 0xf3, 0x7e, 0x3b, 0x3b, 0x03,
	0xc3, 0x70, 0xe9, 0xad, 0x05, 0x57, 0x9c, 0x1c, 0x45, 0xdc, 0x4b, 0xd8, 0x4a, 0x70, 0x4f, 0x8a,
	0x5f, 0x5e, 0xb8, 0xa4, 0x2f, 0x61, 0x70, 0x83, 0x52, 0x06, 0x11, 0x92, 0x09, 0xd8, 0x32, 0x78,
	0x74, 0xac, 0xa9, 0x35, 0x1b, 0xf9, 0xf9, 0x27, 0xbd, 0x80, 0xe3, 0x6b, 0x8c, 0x51, 0xe1, 0x5c,
	0xa2, 0xf0, 0xf1, 0x67, 0x86, 0x52, 0x91, 0x43, 0xe8, 0xb0, 0x50, 0xb3, 0x6c, 0xbf, 0xc3, 0x42,
	0xfa, 0x0e, 0x48, 0x95, 0x24, 0xd7, 0x3c, 0x95, 0x48, 0x5e, 0x40, 0x5f, 0xaa, 0x40, 0x65, 0xd2,
	0xe8, 0x99, 0xc8, 0x54, 0x77, 0x36, 0xd5, 0x53, 0x38, 0xfc, 0x88, 0xaa, 0x5d, 0x7f, 0xa4, 0x19,
	0xbf, 0x6d, 0x38, 0xda, 0x50, 0x8c, 0x7a, 0xed, 0x0c, 0x84, 0x40, 0x37, 0x0d, 0x12, 0xd4, 0xba,
	0x23, 0x5f, 0x7f, 0x6b, 0x3b, 0xf8, 0xe0, 0xd8, 0xc6, 0x0e, 0x3e, 0x10, 0x07, 0x06, 0x41, 0x18,
	0x0a, 0x94, 0xd2, 0xe9, 0x6a, 0xb4, 0x0c, 0xc9, 0x09, 0xf4, 0x30, 0x09, 0x58, 0xec, 0xf4, 0x34,
	0x5e, 0x04, 0xe4, 0x1c, 0x9e, 0xad, 0xb9, 0x50, 0x22, 0x60, 0x6a, 0x91, 0x89, 0xd8, 0xe9, 0xeb,
	0xe4, 0xb8, 0xc4, 0xe6, 0x22, 0x26, 0x67, 0x30, 0x5e, 0x09, 0x0c, 0x14, 0x2e, 0x14, 0x4b, 0xd0,
	0x19, 0x4c, 0xad, 0x59, 0xcf, 0x87, 0x02, 0xfa, 0xca, 0x12, 0xcc, 0x09, 0xd9, 0x3a, 0xdc, 0x10,
	0x86, 0x05, 0xa1, 0x80, 0x72, 0x82, 0xfb, 0x05, 0x06, 0x1f, 0xcc, 0x29, 0xea, 0xae, 0x4e, 0x61,
	0x24, 0xef, 0xb9, 0x50, 0x15, 0x6b, 0x5b, 0xa0, 0xea, 0xc6, 0xde, 0x71, 0xe3, 0x7e, 0x87, 0xf1,
	0x0d, 0x5f, 0xb2, 0x18, 0x6f, 0xef, 0x79, 0xda, 0xbc, 0xac, 0xdc, 0x56, 0x9e, 0x58, 0xa4, 0x59,
	0xb2, 0x44, 0x61, 0x94, 0xc7, 0x1a, 0xfb, 0xac, 0xa1, 0xdd, 0x3f, 0xdb, 0xb5, 0x3f, 0xe7, 0xcf,
	0x62, 0xae, 0x0d, 0xec, 0x7b, 0x16, 0x7f, 0x2d, 0x20, 0x55, 0xd6, 0x7f, 0xd7, 0x39, 0x7a, 0x0a,
	0xc3, 0x8d, 0xad, 0x09, 0xd8, 0x89, 0x8c, 0xca, 0xd9, 0x49, 0x64, 0x44, 0x67, 0x30, 0xb9, 0x53,
	0x02, 0x83, 0x84, 0xa5, 0x51, 0x79, 0x47, 0x27, 0xd0, 0x5b, 0xf1, 0x2c, 0x55, 0xc6, 0x7f, 0x11,
	0xd0, 0xd7, 0x70, 0x5c, 0x61, 0x1a, 0xc1, 0x76, 0xea, 0x2b, 0xe8, 0xde, 0xb2, 0x34, 0x2a, 0xa6,
	0x4b, 0xf0, 0x1f, 0x68, 0xd2, 0x26, 0xd2, 0x79, 0xfe, 0x74, 0xfe, 0xcd, 0x1f, 0x1b, 0x3a, 0xd7,
	0x57, 0xc4, 0x87, 0xb1, 0x99, 0xa8, 0xab, 0xc7, 0x4f, 0x21, 0x39, 0xf3, 0x6a, 0x5b, 0xc1, 0xdb,
	0x1d, 0x49, 0x77, 0xfa, 0x34, 0xa1, 0x38, 0x2e, 0x3d, 0x20, 0xdf, 0x00, 0xb6, 0xed, 0x26, 0xb4,
	0x51, 0xd1, 0x78, 0x31, 0xee, 0xc5, 0x5e, 0x4e, 0x55, 0x78, 0xbb, 0x5f, 0x5a, 0x84, 0x1b, 0x1b,
	0xaa, 0x45, 0xb8, 0xb9, 0xa0, 0xe8, 0x01, 0xb9, 0x83, 0x7e, 0x71, 0xef, 0xe4, 0xbc, 0x51, 0x50,
	0x6f, 0x9d, 0x4b, 0xf7, 0x51, 0x4a, 0xc9, 0x4b, 0x8b, 0xbc, 0x87, 0x61, 0xde, 0x21, 0xdd, 0x85,
	0xe7, 0x8d, 0x9a, 0x3c, 0xe5, 0xb6, 0xc0, 0x3c, 0x8d, 0xe8, 0xc1, 0xcc, 0xba, 0xb4, 0x96, 0x7d,
	0xbd, 0xa7, 0xdf, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x21, 0x07, 0xb6, 0xb3, 0x05, 0x00,
	0x00,
}
