// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

/*
Package go_micro_srv_db is a generated protocol buffer package.

It is generated from these files:
	db.proto

It has these top-level messages:
	Message
	DeleteUserRequest
	DeleteUserResponse
	GetUserRequest
	GetUserResponse
	UpdateUserRequest
	CreateUserRequest
	CreateUserResponse
	UpdateUserResponse
	Response
	StreamingRequest
	StreamingResponse
	Ping
	Pong
*/
package go_micro_srv_db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Say string `protobuf:"bytes,1,opt,name=say" json:"say,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type DeleteUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeleteUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Id     int64  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserResponse) Reset()                    { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()               {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DeleteUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserResponse struct {
	Id          int64                          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string                         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Sex         string                         `protobuf:"bytes,3,opt,name=sex" json:"sex,omitempty"`
	Email       string                         `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	PortraitUrl string                         `protobuf:"bytes,5,opt,name=portrait_url,json=portraitUrl" json:"portrait_url,omitempty"`
	CreateTime  string                         `protobuf:"bytes,6,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime  string                         `protobuf:"bytes,7,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	Address     []*GetUserResponse_Address     `protobuf:"bytes,8,rep,name=address" json:"address,omitempty"`
	Mobile      []*GetUserResponse_MobilePhone `protobuf:"bytes,9,rep,name=mobile" json:"mobile,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserResponse) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *GetUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserResponse) GetPortraitUrl() string {
	if m != nil {
		return m.PortraitUrl
	}
	return ""
}

func (m *GetUserResponse) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *GetUserResponse) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *GetUserResponse) GetAddress() []*GetUserResponse_Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *GetUserResponse) GetMobile() []*GetUserResponse_MobilePhone {
	if m != nil {
		return m.Mobile
	}
	return nil
}

type GetUserResponse_Address struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Shortname string `protobuf:"bytes,2,opt,name=shortname" json:"shortname,omitempty"`
	Address   string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *GetUserResponse_Address) Reset()                    { *m = GetUserResponse_Address{} }
func (m *GetUserResponse_Address) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse_Address) ProtoMessage()               {}
func (*GetUserResponse_Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *GetUserResponse_Address) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponse_Address) GetShortname() string {
	if m != nil {
		return m.Shortname
	}
	return ""
}

func (m *GetUserResponse_Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetUserResponse_MobilePhone struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PhoneNumber string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	Shortname   string `protobuf:"bytes,3,opt,name=shortname" json:"shortname,omitempty"`
}

func (m *GetUserResponse_MobilePhone) Reset()                    { *m = GetUserResponse_MobilePhone{} }
func (m *GetUserResponse_MobilePhone) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse_MobilePhone) ProtoMessage()               {}
func (*GetUserResponse_MobilePhone) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 1} }

func (m *GetUserResponse_MobilePhone) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserResponse_MobilePhone) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *GetUserResponse_MobilePhone) GetShortname() string {
	if m != nil {
		return m.Shortname
	}
	return ""
}

type UpdateUserRequest struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Sex         string `protobuf:"bytes,3,opt,name=sex" json:"sex,omitempty"`
	Email       string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	PortraitUrl string `protobuf:"bytes,5,opt,name=portrait_url,json=portraitUrl" json:"portrait_url,omitempty"`
	CreateTime  string `protobuf:"bytes,6,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime  string `protobuf:"bytes,7,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetPortraitUrl() string {
	if m != nil {
		return m.PortraitUrl
	}
	return ""
}

func (m *UpdateUserRequest) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *UpdateUserRequest) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type CreateUserRequest struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Sex         string `protobuf:"bytes,2,opt,name=sex" json:"sex,omitempty"`
	Email       string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	PortraitUrl string `protobuf:"bytes,4,opt,name=portrait_url,json=portraitUrl" json:"portrait_url,omitempty"`
	CreateTime  string `protobuf:"bytes,5,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime  string `protobuf:"bytes,6,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPortraitUrl() string {
	if m != nil {
		return m.PortraitUrl
	}
	return ""
}

func (m *CreateUserRequest) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *CreateUserRequest) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type CreateUserResponse struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateUserResponse struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Sex         string `protobuf:"bytes,3,opt,name=sex" json:"sex,omitempty"`
	Email       string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	PortraitUrl string `protobuf:"bytes,5,opt,name=portrait_url,json=portraitUrl" json:"portrait_url,omitempty"`
	CreateTime  string `protobuf:"bytes,6,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime  string `protobuf:"bytes,7,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
}

func (m *UpdateUserResponse) Reset()                    { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()               {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserResponse) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *UpdateUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserResponse) GetPortraitUrl() string {
	if m != nil {
		return m.PortraitUrl
	}
	return ""
}

func (m *UpdateUserResponse) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *UpdateUserResponse) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamingRequest struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *StreamingRequest) Reset()                    { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()               {}
func (*StreamingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *StreamingResponse) Reset()                    { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()               {}
func (*StreamingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke int64 `protobuf:"varint,1,opt,name=stroke" json:"stroke,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke int64 `protobuf:"varint,1,opt,name=stroke" json:"stroke,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.db.Message")
	proto.RegisterType((*DeleteUserRequest)(nil), "go.micro.srv.db.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "go.micro.srv.db.DeleteUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "go.micro.srv.db.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "go.micro.srv.db.GetUserResponse")
	proto.RegisterType((*GetUserResponse_Address)(nil), "go.micro.srv.db.GetUserResponse.Address")
	proto.RegisterType((*GetUserResponse_MobilePhone)(nil), "go.micro.srv.db.GetUserResponse.MobilePhone")
	proto.RegisterType((*UpdateUserRequest)(nil), "go.micro.srv.db.UpdateUserRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "go.micro.srv.db.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "go.micro.srv.db.CreateUserResponse")
	proto.RegisterType((*UpdateUserResponse)(nil), "go.micro.srv.db.UpdateUserResponse")
	proto.RegisterType((*Response)(nil), "go.micro.srv.db.Response")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.db.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.db.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.db.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.db.Pong")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xde, 0x24, 0xfd, 0x9d, 0xa0, 0xdd, 0xd6, 0x5a, 0xa1, 0xa8, 0xac, 0xd8, 0xe2, 0xe5, 0x50,
	0x24, 0x94, 0xc3, 0x72, 0xe5, 0x42, 0xa9, 0x84, 0x38, 0x2c, 0x5a, 0x02, 0x15, 0x37, 0xaa, 0xb4,
	0x19, 0x65, 0x23, 0x9a, 0xb8, 0xd8, 0x0e, 0xda, 0x7d, 0x2f, 0x1e, 0x01, 0x9e, 0x84, 0x07, 0x01,
	0xd5, 0x71, 0xda, 0x50, 0x67, 0xdb, 0x2b, 0xdc, 0x3c, 0x33, 0xdf, 0x7c, 0xfe, 0x66, 0xec, 0xb1,
	0xa1, 0x13, 0xcd, 0xfd, 0x15, 0x67, 0x92, 0x91, 0x93, 0x98, 0xf9, 0x69, 0xb2, 0xe0, 0xcc, 0x17,
	0xfc, 0x9b, 0x1f, 0xcd, 0xe9, 0x23, 0x68, 0x5f, 0xa1, 0x10, 0x61, 0x8c, 0xa4, 0x07, 0x8e, 0x08,
	0xef, 0x3c, 0x6b, 0x68, 0x8d, 0xba, 0xc1, 0x7a, 0x49, 0x2f, 0xa0, 0x3f, 0xc1, 0x25, 0x4a, 0x9c,
	0x0a, 0xe4, 0x01, 0x7e, 0xcd, 0x51, 0x48, 0x72, 0x0c, 0x76, 0x12, 0x29, 0x94, 0x13, 0xd8, 0x49,
	0x44, 0x5f, 0x02, 0xa9, 0x82, 0xc4, 0x8a, 0x65, 0x02, 0xc9, 0x43, 0x68, 0x09, 0x19, 0xca, 0x5c,
	0x68, 0x3e, 0x6d, 0xe9, 0x6c, 0x7b, 0x93, 0x3d, 0x84, 0xe3, 0x37, 0x28, 0xf7, 0xf1, 0xff, 0x76,
	0xe0, 0x64, 0x03, 0xd1, 0xec, 0x3b, 0x18, 0x42, 0xa0, 0x91, 0x85, 0x29, 0x2a, 0xde, 0x6e, 0xa0,
	0xd6, 0xaa, 0x1c, 0xbc, 0xf5, 0x1c, 0x5d, 0x0e, 0xde, 0x92, 0x53, 0x68, 0x62, 0x1a, 0x26, 0x4b,
	0xaf, 0xa1, 0x7c, 0x85, 0x41, 0x9e, 0xc0, 0x83, 0x15, 0xe3, 0x92, 0x87, 0x89, 0x9c, 0xe5, 0x7c,
	0xe9, 0x35, 0x55, 0xd0, 0x2d, 0x7d, 0x53, 0xbe, 0x24, 0xe7, 0xe0, 0x2e, 0x38, 0x86, 0x12, 0x67,
	0x32, 0x49, 0xd1, 0x6b, 0x29, 0x04, 0x14, 0xae, 0x8f, 0x49, 0x8a, 0x6b, 0x40, 0xbe, 0x8a, 0x36,
	0x80, 0x76, 0x01, 0x28, 0x5c, 0x0a, 0x30, 0x86, 0x76, 0x18, 0x45, 0x1c, 0x85, 0xf0, 0x3a, 0x43,
	0x67, 0xe4, 0x5e, 0x8e, 0xfc, 0x9d, 0x93, 0xf0, 0x77, 0x6a, 0xf4, 0x5f, 0x15, 0xf8, 0xa0, 0x4c,
	0x24, 0x13, 0x68, 0xa5, 0x6c, 0x9e, 0x2c, 0xd1, 0xeb, 0x2a, 0x8a, 0xe7, 0x07, 0x29, 0xae, 0x14,
	0xfc, 0xfa, 0x86, 0x65, 0x18, 0xe8, 0xdc, 0xc1, 0x7b, 0x68, 0x6b, 0x66, 0xa3, 0x8b, 0x67, 0xd0,
	0x15, 0x37, 0x8c, 0xcb, 0x4a, 0x2b, 0xb7, 0x0e, 0xe2, 0x6d, 0x4b, 0x28, 0x7a, 0x5a, 0x9a, 0x83,
	0xcf, 0xe0, 0x56, 0x76, 0x32, 0x68, 0xd7, 0x0d, 0x5e, 0x07, 0x66, 0x59, 0x9e, 0xce, 0x91, 0x6b,
	0x66, 0x57, 0xf9, 0xde, 0x29, 0xd7, 0xdf, 0x3b, 0x3b, 0x3b, 0x3b, 0xd3, 0x1f, 0x16, 0xf4, 0xa7,
	0xaa, 0x97, 0x7b, 0xee, 0xc9, 0x3f, 0x7f, 0x07, 0xe8, 0x77, 0x0b, 0xfa, 0xaf, 0x15, 0xbe, 0x5a,
	0x46, 0x29, 0xdb, 0x32, 0x65, 0xdb, 0x35, 0xb2, 0x9d, 0x7d, 0xb2, 0x1b, 0x07, 0x65, 0x37, 0x0f,
	0xc9, 0x6e, 0x19, 0xb2, 0x9f, 0x02, 0xa9, 0xaa, 0xae, 0x9f, 0x40, 0xfa, 0xd3, 0x02, 0x52, 0x3d,
	0xa3, 0xff, 0x74, 0x50, 0xe9, 0x19, 0x74, 0x36, 0xe2, 0x7b, 0xe0, 0xa4, 0x22, 0x2e, 0x1f, 0xc4,
	0x54, 0xc4, 0x74, 0x04, 0xbd, 0x0f, 0x92, 0x63, 0x98, 0x26, 0x59, 0x5c, 0x1e, 0xe0, 0x29, 0x34,
	0x17, 0x2c, 0xcf, 0xa4, 0xae, 0xb2, 0x30, 0xe8, 0x33, 0xe8, 0x57, 0x90, 0x9a, 0xb0, 0x1e, 0xfa,
	0x18, 0x1a, 0xd7, 0x49, 0x16, 0x17, 0x4f, 0x26, 0x67, 0x5f, 0x50, 0x87, 0xb5, 0xa5, 0xe2, 0xec,
	0xfe, 0xf8, 0xe5, 0x2f, 0x1b, 0xec, 0xc9, 0x98, 0x04, 0xe0, 0xea, 0xf9, 0x1f, 0xdf, 0xbd, 0x8d,
	0xc8, 0xf9, 0xfd, 0xaf, 0x83, 0xd2, 0x3d, 0x18, 0x1e, 0x7a, 0x3e, 0xe8, 0x11, 0xf9, 0x04, 0xb0,
	0x3d, 0x54, 0x42, 0x8d, 0x0c, 0x63, 0x2a, 0x07, 0x17, 0x7b, 0x31, 0x55, 0xe2, 0xed, 0xa5, 0xaa,
	0x21, 0x36, 0xe6, 0xa4, 0x86, 0xd8, 0xbc, 0x95, 0x05, 0xf1, 0xf6, 0x37, 0xaa, 0x21, 0x36, 0xfe,
	0xb3, 0x1a, 0x62, 0xf3, 0x3b, 0xa3, 0x47, 0xf3, 0x96, 0xfa, 0x40, 0x5f, 0xfc, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x2c, 0xc4, 0xac, 0xb3, 0x4c, 0x07, 0x00, 0x00,
}
